name: sama_bus
description: "A new Flutter project."

publish_to: 'none' # This prevents publishing to pub.dev (good for private projects).

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  flutter_svg: ^2.0.15
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_lints: ^4.0.0 # Linting rules for Flutter projects.
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/

  

