name: sama_bus
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.15
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true


assets:
  - assets/images/